title: Ralph Yang 的吃喝玩乐 - RY'chwl
author: Ralph Yang
email: cyangjob@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  [页面右下角文字]
baseurl: /lifeblog #全局路径，设置为project name
twitter_username: 
github_username:  ycj28c

defaults:
  -
    scope:
      path: "posts" # 空字符串所有的文件。这里指posts文件夹
    values:
      layout: "default"
      theme: minima
      permalink: date  # 这是指博客文章的网址格式

# Build settings
permalink: /:title.html
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
disqus:
  shortname: ycj28cgithubio
